default_config:
logger:
  default: error
  logs:
    custom_components.octoprint_hass: debug



# octoprint_hass:
#   username: my_username
#   password: my_password
#   binary_sensor:
#     - enabled: true
#       name: My custom name
#   sensor:
#     - enabled: true
#       name: My custom name
#   # switch:
#   #   - enabled: true
#   #     name: My custom name
# # host: 192.168.1.212
# # port: 5000